#name, main, version and api are required
name: SimpleMarry
main: SimpleMarry\SimpleMarry
version: 1.1.3
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 4.0.0
- 4.0.0-ALPHA1
- 4.0.0-ALPHA2
- 4.0.0-ALPHA3
- 4.0.0-ALPHA4
- 4.0.0-ALPHA5
load: POSTWORLD
author: Him188
description: Let your game player to enjoy life .
commands:
 结婚:
  description: 结婚 主命令
  usage: "/结婚"
  permission: SimpleMarry.marry
permissions:
 SimpleMarry.marry:
  description: "结婚 主命令"
  default: true