name: RVIP
main: RVIP.MainClass
version: 1.0.0
api: 1.0.0

load: POSTWORLD
author: zmdd
description: RVIP of Rs
commands:
  vip:
    description: RVIP command
    usage: "/vip help"
    permission: Rs.vip.command.vip
  point:
    description: RVIP command
    usage: "/point help"
    permission: Rs.vip.command.help
permissions:
  Rs.vip.command.vip:
    description: Can use it to add/remove/... vip
    default: true
  Rs.vip.command.point:
    description: Can use it to add/remove/... point
    default: true