name: TimeBan
version: 2.0.0
api:
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 4.0.0
- 4.0.0-ALPHA1
- 4.0.0-ALPHA2
- 4.0.0-ALPHA3
- 4.0.0-ALPHA4
- 4.0.0-ALPHA5
main: TimeBan\Main
load: POSTWORLD
author: linger
commands:
 timeban:
  description: "时间ban系命令包"
  usage: "/timeban [set (玩家 日期20160101)/removeall(移除所有)/remove(移除玩家)]"
  permission: TimeBan.
 chatban:
  description: "Chatban系命令包"
  usage: "/chatban [set (玩家 分钟数)/removeall(移除所有)/remove(移除玩家)]"
  permission: TimeBan.
permissions:
 TimeBan.:
  description: "OP允许!"
  default: op