name: OreFinder
main: OreFinder\OreFinder
version: 1.0.0
author: China
api:
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 4.0.0
- 4.0.0-ALPHA1
- 4.0.0-ALPHA2
- 4.0.0-ALPHA3
- 4.0.0-ALPHA4
- 4.0.0-ALPHA5
load: POSTWORLD
commands:
 ores :
  permission: orefinder.find
  description: 找矿石,作者qq2843138797
  usage: /ores
permissions:
 orefinder:
  default: op
  description: op才可以
  children:
   orefinder.find:
    default: op
    description: op的