name: SWorld
main: SWorld\SWorld
version: 1.1.0
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 4.0.0
- 4.0.0-ALPHA1
- 4.0.0-ALPHA2
- 4.0.0-ALPHA3
- 4.0.0-ALPHA4
- 4.0.0-ALPHA5
load: POSTWORLD
author: 18WYJ2 & boybook

commands:
 w:
  description: Change world
  
 lw:
  description: See list of worlds

 load:
  permission: World.load
  description: Load a world

 unload:
  permission: World.unload
  description: Unload a world

  
permissions:
 World:
  default: op
  description: SWorld permission
  children:
     World.load:
      default: op
      description: load a world
     World.unload:
      default: op
      description: unload a world
    