name: BlockWithPlayer
main: BlockWithPlayer\BlockWithPlayer
version: 1.1.0
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 4.0.0
- 4.0.0-ALPHA1
- 4.0.0-ALPHA2
- 4.0.0-ALPHA3
- 4.0.0-ALPHA4
- 4.0.0-ALPHA5
load: STARTUP
author: linger

commands:
 backblock:
  description: "/backblock set [ID] // remove来设置跟随方块"
  usage: "/backblock set [ID] //remove"