name: handboom
main: stark\handboom\Main
version: 1.0.0
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 4.0.0
- 4.0.0-ALPHA1
- 4.0.0-ALPHA2
- 4.0.0-ALPHA3
- 4.0.0-ALPHA4
- 4.0.0-ALPHA5
load: POSTWORLD
author: stark
commands:
 boom:
  description: ""
  usage: "/boom"
  permission: handboom.command.boom
permissions:
 handboom.*:
  description: ""
  default: true
 handboom.command.boom:
  description: "这代表普通玩家也能使用这个指令"
  default: true
